- src/Synapse/Email/EmailService.php
- src/Synapse/Email/SendEmailCommand.php
- src/Synapse/Email/SenderInterface.php
1. The function prototype for `EmailService::setMailMapper()` will no longer specify EmailMapper and will instead specify AbstractMapper.
1. `createFromArray()` method will use the entity returned from the mapper's `getPrototype()` method instead of `EmailEntity`
1. The prototype for `enqueueSendEmailJob()` will require `AbstractEntity` instead of `EmailEntity`
> Make EmailService more generic

- src/Synapse/Mapper/FinderTrait.php
- tests/Test/Synapse/Mapper/FinderTraitTest.php
1. Use  `Zend\Db\Sql\Predicate\NotIn` for NotIn operator in Finder Trait
1. Use  `Zend\Db\Sql\Predicate\IsNull` for NotIn operator in Finder Trait
1. Use  `Zend\Db\Sql\Predicate\IsNotNull` for NotIn operator in Finder Trait
1. `['column', 'IS', null]` is the syntax for accessing the `IS NULL` operator
1. Throw `LogicException` for missing predicates
> Support NOT IN in finder trait

- src/Synapse/Mapper/FinderTrait.php
- tests/Test/Synapse/Mapper/FinderTraitTest.php
There's issue with our FinderTrait in synapse-base. It only happens when a wheres contains an array with exactly 3 elements as a value.
When an application gets a list of entity ids and uses the finder trait to find the entities that correspond to those ids, it adds a ‘where’ clause that looks like `[‘id’ => [1,2,3,4,5,6...]]`
BUT, when it’s an array of exactly 3 elements, it thinks you’re trying to set a where clause with a format like this: `[‘id’, ‘>’, ‘6']`
If you try to do a findAllBy with 3 id's, it will throw an error:
```
"error": "Notice: Undefined variable: predicate",
```
Trevor Boone [10:47 AM] 
If I use the finder trait to search for records using an array of ids, e.g. `’id’ => [1,2,3,4,5,6…]`, it throws an error if I need to find exactly three ids …
> FinderTrait bug when wheres contains an array with exactly 3 elements as a value

- src/Synapse/Stdlib/DataObject.php
1. `setAsFloat` function exists in `DataObject` class, which works like `setAsInt`, but does it with float.
- Make a `setAsFloat` function on the `DataObject` class
> Create setAsFloat function in DataObject

- src/Synapse/Log/LogServiceProvider.php
`LogServiceProvider::getHandlers` function needs to be passed the `$app` reference.
```
[2015-02-10T00:29:50+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[console migrations:run] (app_deploy::default line 7) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '255'
---- Begin output of ./console migrations:run ----
STDOUT: 
STDERR: PHP Warning:  Module 'newrelic' already loaded in Unknown on line 0
PHP Notice:  Undefined variable: app in /srv/www/bodetree/releases/20150210002236/api.bodetree.com/vendor/synapsestudios/synapse-base/src/Synapse/Log/LogServiceProvider.php on line 96
PHP Stack trace:
PHP   1. {main}() /srv/www/bodetree/releases/20150210002236/api.bodetree.com/console:0
PHP   2. require() …
```
> LogServiceProvider causing issues on production deploy

- CHANGELOG.md
- src/Synapse/Controller/AbstractController.php
- src/Synapse/Db/DbServiceProvider.php
- src/Synapse/Db/TransactionAwareInterface.php
- src/Synapse/Db/TransactionAwareTrait.php
- src/Synapse/TestHelper/ControllerTestCase.php
- src/Synapse/TestHelper/InjectMockTransactionTrait.php
The trait will include a setter for injecting a `Synapse\Db\Transaction` object. We'll then add an initializer to auto-inject the object.
Since it will be very common for controllers to wrap method calls in a transaction, AbstractController should implement the interface by default.
- Not QA testable
1. Create interface
1. Create trait
1. Set up initializer
1. Have AbstractController implement the interface
> Add TransactionAwareInterface and TransactionAwareTrait

- src/Synapse/Mapper/FinderTrait.php
- tests/Test/Synapse/Mapper/FinderTraitTest.php
1. `findBy` properly adds an `ORDER BY` statement if the `order` option is specified
- {{list developer tasks here}}
> FinderTrait::findBy supports ORDER BY options

- CHANGELOG.md
- src/Synapse/Mapper/AbstractMapper.php
- src/Synapse/Mapper/InserterTrait.php
- src/Synapse/Mapper/UpdaterTrait.php
- tests/Test/Synapse/Mapper/DatetimeColumnMapper.php
- tests/Test/Synapse/Mapper/InserterTraitTest.php
- tests/Test/Synapse/Mapper/UpdaterTraitTest.php
They will work the same as `createdTimestampColumn` and `updatedTimestampColumn`, only the value set will be a datetime.
1. Dev Tested
- Add properties.
- Update InserterTrait and UpdaterTrait.
- Maybe add a comment saying the timestamp properties are deprecated.
> Add createdDatetimeColumn and updatedDatetimeColumn to AbstractMapper

- CHANGELOG.md
- src/Synapse/Mapper/AbstractMapper.php
- src/Synapse/Mapper/InserterTrait.php
- src/Synapse/Mapper/UpdaterTrait.php
- tests/Test/Synapse/Mapper/DatetimeColumnMapper.php
- tests/Test/Synapse/Mapper/InserterTraitTest.php
- tests/Test/Synapse/Mapper/MapperWithDifferentPrimaryKey.php
- tests/Test/Synapse/Mapper/UpdaterTraitTest.php
Add a property to AbstractMapper called primaryKey. It's default value will be `['id']`. 
Update `UpdaterTrait::updateRow()` to do this:
```
$condition = [];
$arrayCopy = $entity->getArrayCopy();
foreach ($this->primaryKey as $keyColumn) {
$condition[$keyColumn] = $arrayCopy[$keyColumn];
}
```
1. {{list ACs here}}
- {{list developer tasks here}}
> Rewrite UpdaterTrait to support tables whose primary key is not `id`

- src/Synapse/Mapper/AbstractMapper.php
- src/Synapse/Mapper/InserterTrait.php
Add a property to AbstractMapper called autoIncrementColumn with default value `id`.
Change:
```php
if (! $entity->getId()) {
$entity->setId($result->getGeneratedValue());
}
```
to:
```php
if ($this->autoIncrementColumn) {
$entity->exchangeArray([
$this->autoIncrementColumn => $result->getGeneratedValue()
]);
}
```
> Error when inserting into a table that has no `id` column

- src/Synapse/Mapper/AbstractMapper.php
- src/Synapse/Mapper/DeleterTrait.php
- src/Synapse/Mapper/UpdaterTrait.php
Instead of assuming the existence of an `id` property, the DeleterTrait should use the `$primaryKey` property added in #177 to compose the WHERE clause.
1. {{list ACs here}}
- {{list developer tasks here}}
> Update DeleterTrait to use $primaryKey property

- src/Synapse/Mapper/InserterTrait.php
- tests/Test/Synapse/Mapper/InserterTraitTest.php
- tests/Test/Synapse/Mapper/InvalidAutoincrementMapper.php
Error occurs if your entity has no `id` property and you forget to change the $autoIncrementColumn value
> Undefined index error introduced in #180

- CHANGELOG.md
- src/Synapse/Migration/RunMigrationsCommand.php
When errors occur, it is difficult to find what the next migration might be.
1. Logs a "STARTING" message before executing each migration
- Add another writeln in RunMigrationsCommand
> Add starting message to migrations

- CHANGELOG.md
- src/Synapse/Migration/CreateMigrationCommand.php
- tests/Test/Synapse/Migration/CreateMigrationCommandTest.php
Making the files start with a constant string (as classes cannot begin with an integer), followed by the date will allow them to be sortable alphabetically.
1. New migration files are created in a way which sorting by filename shows them in the order they were created.
- Modify CreateMigrationCommand:classname method to use format:
Migration[datetimestamp][PascalCasedDescription]
> Allow for better file naming in migrations

- src/Synapse/OAuth2/ServerServiceProvider.php
In order to overwrite a route you have to use `bind()` values on the route that is being overwritten. So in order to make the OAuth routes overwrite-able `bind()` values need to be set.
1. routes in the `Oauth2\ServerServiceProvider` have bind values
> Add bind() values to OAuth server routes

- src/Synapse/TestHelper/AbstractSecurityAwareTestCase.php
- src/Synapse/TestHelper/ControllerTestCase.php
- src/Synapse/TestHelper/SecurityContextMockInjector.php
- src/Synapse/TestHelper/TransactionMockInjector.php
- src/Synapse/TestHelper/TransactionTraitMockInjector.php
1. `SecurityContextMockInjector` trait exists with all the same functionality of `AbstractSecurityAwareTestCase`.
1. Use `SecurityContextMockInjector` trait in `AbstractSecurityAwareTestCase` and delete the properties and methods in `AbstractSecurityAwareTestCase`. Mark `AbstractSecurityAwareTestCase` as deprecated.
1. Rename `InjectMockTransactionTrait` to `TransactionMockInjector`
> Create SecurityContextMockInjector trait

- src/Synapse/Validator/Constraints/RowExists.php
- src/Synapse/Validator/Constraints/RowExistsValidator.php
- src/Synapse/Validator/Constraints/RowNotExists.php
- src/Synapse/Validator/Constraints/RowNotExistsValidator.php
- tests/Test/Synapse/Validator/Constraints/RowExistsValidatorTest.php
- tests/Test/Synapse/Validator/Constraints/RowNotExistsValidatorTest.php
- tests/Test/Synapse/Validator/Constraints/RowsExistValidatorTest.php
1. For each of those constraints, the default `id` field can be overridden with the `field` option, so that they become checks that "an entity exists with {{ this field }} equal to the given value".
1. Another `additional_fields` option exists which filters the constraint to only look for entities which also contain the given fields with the given values.
1. If `additional_fields` contains the contains a key equal to `field` (or the default field `id` if not provided) an Exception is thrown.
- Modify the three mentioned constraints.
- Test them?
> Allow RowExists, RowsExist, and RowNotExists constraints to match on custom field names

- src/Synapse/Mapper/FinderTrait.php
It says it returns an array, but it actually returns an EntityIterator.
> `@return` tag for FinderTrait::findAllBy is incorrect

- src/Synapse/Stdlib/DataObject.php
1. In `DataObject` the `setAsInteger`, `setAsBoolean`, and `setAsString` methods all `return $this;` at the end.
- Add `return $this;` to end of said methods.
- Just realized they don't match the magic setters...that's all.
> Data Object: Add support for fluent interface in setAs* methods

- src/Synapse/Validator/Constraints/RowExists.php
- src/Synapse/Validator/Constraints/RowExistsValidator.php
- src/Synapse/Validator/Constraints/RowNotExists.php
- src/Synapse/Validator/Constraints/RowNotExistsValidator.php
- tests/Test/Synapse/Validator/Constraints/AbstractRowExistsTestCase.php
- tests/Test/Synapse/Validator/Constraints/RowExistsTest.php
- tests/Test/Synapse/Validator/Constraints/RowExistsValidatorTest.php
- tests/Test/Synapse/Validator/Constraints/RowNotExistsValidatorTest.php
- tests/Test/Synapse/Validator/Constraints/RowsExistValidatorTest.php
In #142, RowExists (and family) were made more flexible by allowing custom `$wheres` via a callback or custom field.
However, the case was not provided for where no `field` or `filterCallback` are specified. (Meaning the developer intends for the default `id` field to be used.)
> RowExists breaks if trying to default to Field ID

- src/Synapse/Application/Services.php
- src/Synapse/TestHelper/TimeMockInjector.php
- src/Synapse/Time/Time.php
- src/Synapse/Time/TimeAwareInterface.php
- src/Synapse/Time/TimeAwareTrait.php
- src/Synapse/Time/TimeServiceProvider.php
Relying on the return values of the actual `time` and `date` functions in tests can result in non-deterministic tests, especially when testing edge cases. We should use our *AwareInterface pattern to inject a custom Time object in classes. The Time class will contain passthrough `date` and `time` methods.
1. Not QA testable
- Add TimeAwareInterface with setTimeObject method
- Add TimeAwareTrait
- Add TimeMockInjector trait with injectMockTimeObject method.
> Facilitate testing of time-related logic with TimeAwareInterface

- src/Synapse/Validator/Constraints/RowExists.php
- tests/Test/Synapse/Validator/Constraints/RowExistsTest.php
RowExists constraint is giving an error message when passing in a `field`
```
ContextErrorException in RowExists.php line 43:
Notice: Undefined variable: self
```
Change `$self` to `self`
> RowExists constraint gives ContextErrorException when passing field in the options

- UPGRADE_GUIDE.md
- src/Synapse/Mapper/FinderTrait.php
- src/Synapse/Mapper/InserterTrait.php
- src/Synapse/Mapper/UpdaterTrait.php
- tests/Test/Synapse/Mapper/InserterTraitTest.php
In #107, methods in the `InserterTrait` and `UpdaterTrait` were extracted to encapsulate the database writing logic so that children could overwrite `insert` and `update` without rewriting that logic.
Since then, logic has been added to `insertRow` and `updateRow` to set timestamp columns. This logic belongs in `insert` and `update`, because it's uncorrelated with database interaction.
In order to separate concerns more clearly, all auto-setting of columns should be done in `insert` and `update`. `insertRow` and `updateRow` should only perform database interactions. (The only exception is that `insertRow` should set the auto-generated ID.)
1. Auto timestamp setting in `InserterTrait` and `UpdaterTrait` is moved to `insert` and `update` methods.
1. `$values` are no longer passed to …
> V2: Focus insertRow and updateRow methods

- src/Synapse/Validator/Constraints/RowExists.php
- tests/Test/Synapse/Validator/Constraints/RowNotExistsTest.php
The RowNotExists constraint returns the FIELD_MESSAGE from RowExists if no custom message is supplied. 
Line 43 of RowExists.php is `$this->message = self::FIELD_MESSAGE;`
Should be changed to `$this->message = static::FIELD_MESSAGE;`
> RowNotExists constraint returns message from RowExists if no message is supplied

- UPGRADE_GUIDE.md
- src/Synapse/Security/SecurityAwareInterface.php
- src/Synapse/Security/SecurityAwareTrait.php
- src/Synapse/User/UserController.php
Method names should be verbs, not nouns.
> v2: Change user() to getUser() in SecurityAwareTrait

- src/Synapse/Validator/Constraints/RowExists.php
RowExists was fixed as part of 2.0.0, but older projects are on 1.x, so to maintain backwards compatibility we should fix this in 1.4 as well.
> Patch 1.4.x to fix RowExists for older projects

- src/Synapse/User/RoleService.php
- tests/Test/Synapse/User/RoleServiceTest.php
1. Whenever `RoleService::addRoleForUser` is called, it actually sets the role on the user.
- Modify that class.
- None
> Set role on user entity, not just database, in role service

- src/Synapse/User/UserRegistrationValidator.php
It's possible to successfully submit the Create User endpoint with an empty string for the email address. The email constraint doesn't check whether the value is blank / empty string.
Add the NotBlank constraint.
> Can create a user with an empty string for the email address

- src/Synapse/Install/GenerateInstallCommand.php
It seems that our convention is to not end paths defined in `console` and `index.php` with trailing slashes, yet that assumption is made [here](https://github.com/synapsestudios/synapse-base/blob/master/src/Synapse/Install/GenerateInstallCommand.php#L162) and [here](https://github.com/synapsestudios/synapse-base/blob/master/src/Synapse/Install/GenerateInstallCommand.php#L189). As a result, the generated DB files will be placed at the root directory with the prefix `data` instead of in the `data` directory.
> install:generate assumes that DATADIR ends in a trailing slash

- src/Synapse/Validator/AbstractArrayValidator.php
- tests/Test/Synapse/Validator/AbstractArrayValidatorTest.php
- tests/Test/Synapse/Validator/ArrayValidator.php
1. When fields are missing from validators that extend the AbstractArrayValidator, return `MISSING` as the error message rather than the default, `This field is missing.`.
- Add `missingFieldsMessage` to `Collection` constraint options.
- Since we're doing i18n on the front-ends, we're moving to this approach for validation errors.
> Return more "constant-ey" validation message when fields are missing in AbstractArrayValidator

- src/Synapse/OAuth2/OAuthController.php
- src/Synapse/OAuth2/ServerServiceProvider.php
- tests/Test/Synapse/OAuth2/OAuthControllerTest.php
1. An app configuration setting exists to disable login without verifying your account
1. When this flag is set, unverified accounts cannot log in
1. If the "enabled" flag in the database is not set, account cannot log in
- Add config setting
- Update `Synapse\OAuth2\ServerServiceProvider` to pass the configuration setting into the OAuthController
- Update `Synapse\OAuth2\OAuthController` to check if the config setting is true and if so, check if the "verified" flag is set on the user entity before allowing login
- Update `Synapse\OAuth2\OAuthController` to check if the user's enabled flag is set before allowing login
- Update tests where necessary
> Configuration setting for disabling login before email verification

- src/Synapse/Email/AbstractSender.php
- tests/Test/Synapse/Email/AbstractSenderTest.php
Ran into this issue on a production install.
If the email whitelist is empty, all emails will be sent to the trap, but if the trap is `null` (which it is by default) then `AbstractSender::injectIntoTrapAddress` will result in this error:
```
PHP Notice:  Undefined offset: 1 in /srv/www/api/releases/20150511181249/vendor/synapsestudios/synapse-base/src/Synapse/Email/AbstractSender.php on line 74
```
Here's the offending code:
```PHP
list($trapName, $trapDomain) = explode('@', $trapAddress);
```
- Expected behavior: If the trap isn't an email address, then an exception is thrown saying, "You need a trap email address".
> Email Whitelist / Trapping Broken

- src/Synapse/CliCommand/AbstractCliCommand.php
- tests/Test/Synapse/CliCommand/CliCommand.php
1. Pass `CliCommandOptions $options` as parameter to `AbstractCliCommand::getBaseCommand()` definition
> Pass CliCommandOptions to AbstractCliCommand::getBaseCommand()

- src/Synapse/User/ResetPasswordController.php
- src/Synapse/User/UserController.php
- src/Synapse/User/UserService.php
- src/Synapse/User/UserValidator.php
- src/Synapse/User/VerifyRegistrationController.php
- tests/Test/Synapse/User/UserControllerTest.php
- tests/Test/Synapse/User/UserServiceTest.php
Many of our endpoints are set up to return plaintext responses, but this is not as simply readable by the front end app as JSON.
1. The Reset Password endpoint (`PUT /user/reset-password`) returns JSON error instead of plaintext when the password is empty.
1. The Create User endpoint (`POST /users`) returns JSON error instead of plaintext when the email address is not unique.
1. The Create User endpoint (`POST /users`) returns JSON error instead of plaintext when the email address is not unique.
1. The Edit User endpoint (`POST /users`) returns JSON error instead of plaintext when (1) the current password is wrong/not provided, (2) the email or new password is empty, and (3) the email address is not unique.
1. The Verify Registration endpoint (`POST /users/{id}/verify-registration`) …
> Return JSON responses only

- src/Synapse/OAuth2/OAuthController.php
- src/Synapse/User/UserEntity.php
It makes no sense for them to be strings. We should be able to write `if ($user->getEnabled())...`.
Will need to update [here](https://github.com/synapsestudios/synapse-base/blob/master/src/Synapse/OAuth2/OAuthController.php#L157) and [here](https://github.com/synapsestudios/synapse-base/blob/master/src/Synapse/OAuth2/OAuthController.php#L161).
> UserEntity's `enabled` and `verified` values should be set as booleans 

- src/Synapse/Security/Firewall/OAuth2OptionalListener.php
When hitting a route with `oauth-optional` set in the firewalls and the frontend having an expired oauth token, Silex will redirect to `/login`. The frontend gets confused and sad. It should instead return an unauthorized error so the frontend can request a new token.
It redirects to login because that's the default `login_path` set in `Silex\Provider\SecurityServiceProvider`.
We don't want to "fix" this path -- we just want to prevent the OauthOptional listener from redirecting to the login path in the first place.
> Silex causes requests with expired access tokens to be 302 redirected to /login

- src/Synapse/OAuth2/OAuthController.php
When you set requireVerificiation=true in the app config, it applies to the HTML login form endpoint (eg, Lively) but not to the token endpoint that the frontend uses to authenticate. This check should be done here as well.
> Required verification config setting doesn't work on token endpoint

- src/Synapse/OAuth2/OAuthController.php
- tests/Test/Synapse/OAuth2/OAuthControllerTest.php
The token request response should be checked first, then we can look up the status of the user. The Lively form also calls this token function as part of the authentication flow, so we don't need to do it in two places.
> Fix user verification bug

- composer.json
- composer.lock
- src/Synapse/Command/CommandServiceProvider.php
- src/Synapse/Log/LogServiceProvider.php
Rollbar is not flushing errors as the close() method is never called.
Easy fix would be to turn batch off.
- Credentials: {{username / password (remove if not applicable)}}
- URL: {{url where problem occurs, remove if not applicable}}
- Note: {{relevant information like related issues, remove if not applicable}}
- Console Error: {{expand and copy from the console (include line error too), remove if not applicable}}
> Rollbar does not flush errors

- src/Synapse/Log/Handler/RollbarHandler.php
- src/Synapse/Log/LogServiceProvider.php
1. The log threshold for rollbar can be provided by the rollbar configuration
1. if no log threshold is provided in configuration the default to `Logger::ERROR`
This probably should be done more generally for all our log handlers but I'm not super into doing that right now
> Allow rollbar error level to be set in configuration

- src/Synapse/Log/Handler/RollbarHandler.php
```
==> default: STDERR: PHP Fatal error:  Class 'Synapse\Log\Handler\Logger' not found in /vagrant/vendor/synapsestudios/synapse-base/src/Synapse/Log/Handler/RollbarHandler.php on line 45
==> default: PHP Stack trace:
==> default: PHP   1. {main}() /vagrant/console:0
==> default: PHP   2. require() /vagrant/console:16
==> default: PHP   3. Synapse\Application\Services->register() /vagrant/bootstrap.php:35
==> default: PHP   4. Silex\Application->register() /vagrant/vendor/synapsestudios/synapse-base/src/Synapse/Application/Services.php:18
==> default: PHP   5. Synapse\Log\LogServiceProvider->register() /vagrant/vendor/silex/silex/src/Silex/Application.php:169
==> default: PHP   6. Synapse\Log\LogServiceProvider->getHandlers() /vagrant/vendor/synapsestudios/synapse-base/src/Synapse/Log/Log …
```
> Add missing use statement to RollbarHandler

- shippable.yml
- src/Synapse/ApplicationInitializer.php
1. Environment can be set to `beta`
1. If `APP_ENV` isn't set or isn't one of the available options, throw an exception
> Add Beta Environment

- src/Synapse/Mapper/InserterTrait.php
The error message for when the autoIncrement column is missing from an entity is `0`
https://github.com/synapsestudios/synapse-base/blob/master/src/Synapse/Mapper/InserterTrait.php#L51
> InserterTrait: LogicException: 0 when autoIncrement column is missing

- src/Synapse/Entity/AbstractEntity.php
- src/Synapse/Mapper/UpdaterTrait.php
- src/Synapse/TestHelper/MapperTestCase.php
- src/Synapse/TestHelper/WebTestCase.php
- tests/Test/Synapse/Mapper/UpdaterTraitTest.php
Currently, an update call overwrites all data in a record.  Doing this can easily cause race conditions if two different api calls changes different fields in the same record.
To do this properly, we should keep track of "dirty" fields and only update those that have changed.
> Mapper update method should only update changed fields

- src/Synapse/Entity/AbstractEntity.php
- src/Synapse/Mapper/AbstractMapper.php
- src/Synapse/Mapper/FinderTrait.php
- src/Synapse/Mapper/Hydrator/ArraySerializable.php
- src/Synapse/TestHelper/MapperTestCase.php
- tests/Test/Synapse/Mapper/FinderTraitTest.php
- tests/Test/Synapse/Mapper/UpdaterTraitTest.php
Will need to extend the hydrator to ensure entity is not dirty when hydrated.
This causes issues when using the new `patch()` method
> Hydrating marks properties as dirty
